# Generated by Django 4.0.4 on 2022-05-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_orderitem_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymentStatus',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='lastUpdate',
            new_name='last_update',
        ),
    ]
